// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "short_name", Type: field.TypeString},
		{Name: "author_name", Type: field.TypeString, Default: ""},
		{Name: "author_url", Type: field.TypeString, Default: ""},
		{Name: "access_token", Type: field.TypeString},
		{Name: "auth_url", Type: field.TypeString, Default: ""},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "account_access_token",
				Unique:  true,
				Columns: []*schema.Column{AccountsColumns[4]},
			},
		},
	}
	// PagesColumns holds the columns for the "pages" table.
	PagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeInt},
		{Name: "path", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeJSON},
		{Name: "url", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "author_name", Type: field.TypeString, Default: ""},
		{Name: "author_url", Type: field.TypeString, Default: ""},
		{Name: "image_url", Type: field.TypeString, Default: ""},
		{Name: "views", Type: field.TypeInt, Default: 0},
	}
	// PagesTable holds the schema information for the "pages" table.
	PagesTable = &schema.Table{
		Name:       "pages",
		Columns:    PagesColumns,
		PrimaryKey: []*schema.Column{PagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "page_path",
				Unique:  true,
				Columns: []*schema.Column{PagesColumns[2]},
			},
		},
	}
	// PageViewsColumns holds the columns for the "page_views" table.
	PageViewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "page_id", Type: field.TypeInt},
		{Name: "path", Type: field.TypeString},
		{Name: "year", Type: field.TypeInt},
		{Name: "month", Type: field.TypeInt},
		{Name: "day", Type: field.TypeInt},
		{Name: "hour", Type: field.TypeInt},
		{Name: "views", Type: field.TypeInt, Default: 0},
	}
	// PageViewsTable holds the schema information for the "page_views" table.
	PageViewsTable = &schema.Table{
		Name:       "page_views",
		Columns:    PageViewsColumns,
		PrimaryKey: []*schema.Column{PageViewsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "pageview_page_id",
				Unique:  false,
				Columns: []*schema.Column{PageViewsColumns[1]},
			},
			{
				Name:    "pageview_path",
				Unique:  false,
				Columns: []*schema.Column{PageViewsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		PagesTable,
		PageViewsTable,
	}
)

func init() {
}
