// Code generated by ent, DO NOT EDIT.

package ent

import (
	"telegraph/storage_repo/ent/account"
	"telegraph/storage_repo/ent/page"
	"telegraph/storage_repo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescShortName is the schema descriptor for short_name field.
	accountDescShortName := accountFields[0].Descriptor()
	// account.ShortNameValidator is a validator for the "short_name" field. It is called by the builders before save.
	account.ShortNameValidator = accountDescShortName.Validators[0].(func(string) error)
	// accountDescAuthorName is the schema descriptor for author_name field.
	accountDescAuthorName := accountFields[1].Descriptor()
	// account.DefaultAuthorName holds the default value on creation for the author_name field.
	account.DefaultAuthorName = accountDescAuthorName.Default.(string)
	// accountDescAuthorURL is the schema descriptor for author_url field.
	accountDescAuthorURL := accountFields[2].Descriptor()
	// account.DefaultAuthorURL holds the default value on creation for the author_url field.
	account.DefaultAuthorURL = accountDescAuthorURL.Default.(string)
	// accountDescAccessToken is the schema descriptor for access_token field.
	accountDescAccessToken := accountFields[3].Descriptor()
	// account.AccessTokenValidator is a validator for the "access_token" field. It is called by the builders before save.
	account.AccessTokenValidator = accountDescAccessToken.Validators[0].(func(string) error)
	// accountDescAuthURL is the schema descriptor for auth_url field.
	accountDescAuthURL := accountFields[4].Descriptor()
	// account.DefaultAuthURL holds the default value on creation for the auth_url field.
	account.DefaultAuthURL = accountDescAuthURL.Default.(string)
	pageFields := schema.Page{}.Fields()
	_ = pageFields
	// pageDescPath is the schema descriptor for path field.
	pageDescPath := pageFields[1].Descriptor()
	// page.PathValidator is a validator for the "path" field. It is called by the builders before save.
	page.PathValidator = pageDescPath.Validators[0].(func(string) error)
	// pageDescTitle is the schema descriptor for title field.
	pageDescTitle := pageFields[2].Descriptor()
	// page.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	page.TitleValidator = pageDescTitle.Validators[0].(func(string) error)
	// pageDescContent is the schema descriptor for content field.
	pageDescContent := pageFields[3].Descriptor()
	// page.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	page.ContentValidator = pageDescContent.Validators[0].(func(string) error)
	// pageDescURL is the schema descriptor for url field.
	pageDescURL := pageFields[4].Descriptor()
	// page.DefaultURL holds the default value on creation for the url field.
	page.DefaultURL = pageDescURL.Default.(string)
	// pageDescDescription is the schema descriptor for description field.
	pageDescDescription := pageFields[5].Descriptor()
	// page.DefaultDescription holds the default value on creation for the description field.
	page.DefaultDescription = pageDescDescription.Default.(string)
	// pageDescAuthorName is the schema descriptor for author_name field.
	pageDescAuthorName := pageFields[6].Descriptor()
	// page.DefaultAuthorName holds the default value on creation for the author_name field.
	page.DefaultAuthorName = pageDescAuthorName.Default.(string)
	// pageDescAuthorURL is the schema descriptor for author_url field.
	pageDescAuthorURL := pageFields[7].Descriptor()
	// page.DefaultAuthorURL holds the default value on creation for the author_url field.
	page.DefaultAuthorURL = pageDescAuthorURL.Default.(string)
	// pageDescImageURL is the schema descriptor for image_url field.
	pageDescImageURL := pageFields[8].Descriptor()
	// page.DefaultImageURL holds the default value on creation for the image_url field.
	page.DefaultImageURL = pageDescImageURL.Default.(string)
	// pageDescViews is the schema descriptor for views field.
	pageDescViews := pageFields[9].Descriptor()
	// page.DefaultViews holds the default value on creation for the views field.
	page.DefaultViews = pageDescViews.Default.(int)
}
