// Code generated by ent, DO NOT EDIT.

package ent

import (
	"telegraph/storage_repo/ent/account"
	"telegraph/storage_repo/ent/page"
	"telegraph/storage_repo/ent/pageview"
	"telegraph/storage_repo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescShortName is the schema descriptor for short_name field.
	accountDescShortName := accountFields[0].Descriptor()
	// account.ShortNameValidator is a validator for the "short_name" field. It is called by the builders before save.
	account.ShortNameValidator = accountDescShortName.Validators[0].(func(string) error)
	// accountDescAuthorName is the schema descriptor for author_name field.
	accountDescAuthorName := accountFields[1].Descriptor()
	// account.DefaultAuthorName holds the default value on creation for the author_name field.
	account.DefaultAuthorName = accountDescAuthorName.Default.(string)
	// accountDescAuthorURL is the schema descriptor for author_url field.
	accountDescAuthorURL := accountFields[2].Descriptor()
	// account.DefaultAuthorURL holds the default value on creation for the author_url field.
	account.DefaultAuthorURL = accountDescAuthorURL.Default.(string)
	// accountDescAccessToken is the schema descriptor for access_token field.
	accountDescAccessToken := accountFields[3].Descriptor()
	// account.AccessTokenValidator is a validator for the "access_token" field. It is called by the builders before save.
	account.AccessTokenValidator = accountDescAccessToken.Validators[0].(func(string) error)
	// accountDescAuthURL is the schema descriptor for auth_url field.
	accountDescAuthURL := accountFields[4].Descriptor()
	// account.DefaultAuthURL holds the default value on creation for the auth_url field.
	account.DefaultAuthURL = accountDescAuthURL.Default.(string)
	pageFields := schema.Page{}.Fields()
	_ = pageFields
	// pageDescPath is the schema descriptor for path field.
	pageDescPath := pageFields[1].Descriptor()
	// page.PathValidator is a validator for the "path" field. It is called by the builders before save.
	page.PathValidator = pageDescPath.Validators[0].(func(string) error)
	// pageDescTitle is the schema descriptor for title field.
	pageDescTitle := pageFields[2].Descriptor()
	// page.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	page.TitleValidator = pageDescTitle.Validators[0].(func(string) error)
	// pageDescURL is the schema descriptor for url field.
	pageDescURL := pageFields[4].Descriptor()
	// page.DefaultURL holds the default value on creation for the url field.
	page.DefaultURL = pageDescURL.Default.(string)
	// pageDescDescription is the schema descriptor for description field.
	pageDescDescription := pageFields[5].Descriptor()
	// page.DefaultDescription holds the default value on creation for the description field.
	page.DefaultDescription = pageDescDescription.Default.(string)
	// pageDescAuthorName is the schema descriptor for author_name field.
	pageDescAuthorName := pageFields[6].Descriptor()
	// page.DefaultAuthorName holds the default value on creation for the author_name field.
	page.DefaultAuthorName = pageDescAuthorName.Default.(string)
	// pageDescAuthorURL is the schema descriptor for author_url field.
	pageDescAuthorURL := pageFields[7].Descriptor()
	// page.DefaultAuthorURL holds the default value on creation for the author_url field.
	page.DefaultAuthorURL = pageDescAuthorURL.Default.(string)
	// pageDescImageURL is the schema descriptor for image_url field.
	pageDescImageURL := pageFields[8].Descriptor()
	// page.DefaultImageURL holds the default value on creation for the image_url field.
	page.DefaultImageURL = pageDescImageURL.Default.(string)
	// pageDescViews is the schema descriptor for views field.
	pageDescViews := pageFields[9].Descriptor()
	// page.DefaultViews holds the default value on creation for the views field.
	page.DefaultViews = pageDescViews.Default.(int)
	pageviewFields := schema.PageView{}.Fields()
	_ = pageviewFields
	// pageviewDescPath is the schema descriptor for path field.
	pageviewDescPath := pageviewFields[1].Descriptor()
	// pageview.PathValidator is a validator for the "path" field. It is called by the builders before save.
	pageview.PathValidator = pageviewDescPath.Validators[0].(func(string) error)
	// pageviewDescYear is the schema descriptor for year field.
	pageviewDescYear := pageviewFields[2].Descriptor()
	// pageview.YearValidator is a validator for the "year" field. It is called by the builders before save.
	pageview.YearValidator = func() func(int) error {
		validators := pageviewDescYear.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(year int) error {
			for _, fn := range fns {
				if err := fn(year); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageviewDescMonth is the schema descriptor for month field.
	pageviewDescMonth := pageviewFields[3].Descriptor()
	// pageview.MonthValidator is a validator for the "month" field. It is called by the builders before save.
	pageview.MonthValidator = func() func(int) error {
		validators := pageviewDescMonth.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(month int) error {
			for _, fn := range fns {
				if err := fn(month); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageviewDescDay is the schema descriptor for day field.
	pageviewDescDay := pageviewFields[4].Descriptor()
	// pageview.DayValidator is a validator for the "day" field. It is called by the builders before save.
	pageview.DayValidator = func() func(int) error {
		validators := pageviewDescDay.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(day int) error {
			for _, fn := range fns {
				if err := fn(day); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageviewDescHour is the schema descriptor for hour field.
	pageviewDescHour := pageviewFields[5].Descriptor()
	// pageview.HourValidator is a validator for the "hour" field. It is called by the builders before save.
	pageview.HourValidator = func() func(int) error {
		validators := pageviewDescHour.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(hour int) error {
			for _, fn := range fns {
				if err := fn(hour); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageviewDescViews is the schema descriptor for views field.
	pageviewDescViews := pageviewFields[6].Descriptor()
	// pageview.DefaultViews holds the default value on creation for the views field.
	pageview.DefaultViews = pageviewDescViews.Default.(int)
	// pageview.ViewsValidator is a validator for the "views" field. It is called by the builders before save.
	pageview.ViewsValidator = pageviewDescViews.Validators[0].(func(int) error)
}
