// Code generated by ent, DO NOT EDIT.

package pageview

const (
	// Label holds the string label denoting the pageview type in the database.
	Label = "page_view"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPageID holds the string denoting the page_id field in the database.
	FieldPageID = "page_id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldMonth holds the string denoting the month field in the database.
	FieldMonth = "month"
	// FieldDay holds the string denoting the day field in the database.
	FieldDay = "day"
	// FieldHour holds the string denoting the hour field in the database.
	FieldHour = "hour"
	// FieldViews holds the string denoting the views field in the database.
	FieldViews = "views"
	// Table holds the table name of the pageview in the database.
	Table = "page_views"
)

// Columns holds all SQL columns for pageview fields.
var Columns = []string{
	FieldID,
	FieldPageID,
	FieldPath,
	FieldYear,
	FieldMonth,
	FieldDay,
	FieldHour,
	FieldViews,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// YearValidator is a validator for the "year" field. It is called by the builders before save.
	YearValidator func(int) error
	// MonthValidator is a validator for the "month" field. It is called by the builders before save.
	MonthValidator func(int) error
	// DayValidator is a validator for the "day" field. It is called by the builders before save.
	DayValidator func(int) error
	// HourValidator is a validator for the "hour" field. It is called by the builders before save.
	HourValidator func(int) error
	// DefaultViews holds the default value on creation for the "views" field.
	DefaultViews int
	// ViewsValidator is a validator for the "views" field. It is called by the builders before save.
	ViewsValidator func(int) error
)
